spring.liquibase.change-log=classpath:/migration/master-changelog.xml

spring.datasource.url=${DATASOURCE_URL:}
spring.datasource.username=${DATASOURCE_USERNAME:}
spring.datasource.password=${DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.Secret=${JWT_SECRET}
jwt.access.secret=${JWT_ACCESS_SECRET}
jwt.access.token.time.to.live=3600000
jwt.refresh.secret=${JWT_REFRESH_SECRET}
jwt.refresh.token.time.to.live=604800000

spring.mail.default-encoding=UTF-8
spring.mail.host=smtp.gmail.com
spring.mail.username=${USERNAME_MAIL:}
spring.mail.password=${PASSWORD_MAIL:}
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.test-connection=false

spring.data.redis.port=6379
spring.data.redis.host=localhost